# This is a basic workflow to help you get started with Actions

name: integratevault

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
env:
  APP_NAME: frontend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: |-
      ${{
        github.ref_name == 'main'             && 'production'
      || contains(github.ref_name, 'release/') && 'staging'
      ||                                         'develop'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://demo-vault.tekos.ovh
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              kv/data/prod/sample_app AWS_ACCESS_KEY_ID | AWS_ACCESS_KEY_ID ;
              kv/data/prod/sample_app AWS_SECRET_ACCESS_KEY | AWS_SECRET_ACCESS_KEY ;
              kv/data/prod/sample_app postgres_uri
              
      - name: Run a one-line script
        run: |
          echo "aws secret ${{ env.AWS_SECRET_ACCESS_KEY }}"
          echo "aws key ${{ env.AWS_ACCESS_KEY_ID }}"
          echo "postgres uri ${{ env.postgres_uri }}"
  
