# This is a basic workflow to help you get started with Actions

name: multienvironment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:
  issue_comment:                                     
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
env:
  APP_NAME: frontend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: |-
      ${{
        github.ref_name == 'main'             && 'production'
      || contains(github.ref_name, 'release/') && 'staging'
      ||                                         'develop'
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo "ref name is ${{ github.ref_name }}"
          echo "run on ${{ vars.ENVIRONMENT_NAME }} environment"
  
  # build-prod:
  #   environment: production
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Run a one-line script
  #       run: |
  #         echo "run on ${{ vars.ENVIRONMENT_NAME }} environment"
  #         echo "application name is ${{ env.APP_NAME }}"
