# This is a basic workflow to help you get started with Actions

name: multienvironment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  workflow_dispatch:
  issue_comment:                                     
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab
env:
  APP_NAME: frontend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      USE_VARIABLES: ${{ steps.running_project.outputs.USE_VARIABLES }}
    steps:
      - name: Define running project
        id: running_project
        run: |
          if [ "$USE_VARIABLES" == "" ]; then
            echo 'USE_VARIABLES="null"' >> "$GITHUB_OUTPUT"
          else
            echo 'USE_VARIABLES="$USE_VARIABLES"' >> "$GITHUB_OUTPUT"
          fi
        env:
          USE_VARIABLES: ${{ vars.USE_VARIABLES }}
  build:
    environment: |-
      ${{
        github.ref_name == 'main'             && 'production'
      || contains(github.ref_name, 'release/') && 'staging'
      ||                                         'develop'
      }}
    runs-on: ubuntu-latest
    needs: define-matrix
    if: ${{ needs.define-matrix.outputs.USE_VARIABLES != 'null' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo "${{secrets.USERNAME }}" >> output.json 
          echo "${{ secrets.PASSWORD }}" >> output.json
          echo "ref name is ${{ github.ref_name }}"
          echo "run on ${{ vars.ENVIRONMENT_NAME }} environment"
          

